// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: coordinator_orchestration.proto

package coordinatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Participant struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdentityPublicKeyHex string                 `protobuf:"bytes,2,opt,name=identity_public_key_hex,json=identityPublicKeyHex,proto3" json:"identity_public_key_hex,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_coordinator_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_coordinator_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *Participant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Participant) GetIdentityPublicKeyHex() string {
	if x != nil {
		return x.IdentityPublicKeyHex
	}
	return ""
}

type KeygenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Threshold     uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Participants  []*Participant         `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenRequest) Reset() {
	*x = KeygenRequest{}
	mi := &file_coordinator_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenRequest) ProtoMessage() {}

func (x *KeygenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenRequest.ProtoReflect.Descriptor instead.
func (*KeygenRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *KeygenRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *KeygenRequest) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *KeygenRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *KeygenRequest) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type SignRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Protocol           string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Threshold          uint32                 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	WalletId           string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	SigningInputHex    string                 `protobuf:"bytes,4,opt,name=signing_input_hex,json=signingInputHex,proto3" json:"signing_input_hex,omitempty"`
	Participants       []*Participant         `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	DerivationPath     []uint32               `protobuf:"varint,6,rep,packed,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	DerivationDeltaHex string                 `protobuf:"bytes,7,opt,name=derivation_delta_hex,json=derivationDeltaHex,proto3" json:"derivation_delta_hex,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_coordinator_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *SignRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SignRequest) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SignRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SignRequest) GetSigningInputHex() string {
	if x != nil {
		return x.SigningInputHex
	}
	return ""
}

func (x *SignRequest) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *SignRequest) GetDerivationPath() []uint32 {
	if x != nil {
		return x.DerivationPath
	}
	return nil
}

func (x *SignRequest) GetDerivationDeltaHex() string {
	if x != nil {
		return x.DerivationDeltaHex
	}
	return ""
}

type SessionLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionLookup) Reset() {
	*x = SessionLookup{}
	mi := &file_coordinator_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionLookup) ProtoMessage() {}

func (x *SessionLookup) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionLookup.ProtoReflect.Descriptor instead.
func (*SessionLookup) Descriptor() ([]byte, []int) {
	return file_coordinator_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *SessionLookup) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RequestAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccepted) Reset() {
	*x = RequestAccepted{}
	mi := &file_coordinator_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccepted) ProtoMessage() {}

func (x *RequestAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccepted.ProtoReflect.Descriptor instead.
func (*RequestAccepted) Descriptor() ([]byte, []int) {
	return file_coordinator_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *RequestAccepted) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RequestAccepted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestAccepted) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RequestAccepted) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RequestAccepted) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SessionResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Completed            bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	SessionId            string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId                string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKeyHex         string                 `protobuf:"bytes,4,opt,name=public_key_hex,json=publicKeyHex,proto3" json:"public_key_hex,omitempty"`
	SignatureHex         string                 `protobuf:"bytes,5,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	SignatureRecoveryHex string                 `protobuf:"bytes,6,opt,name=signature_recovery_hex,json=signatureRecoveryHex,proto3" json:"signature_recovery_hex,omitempty"`
	RHex                 string                 `protobuf:"bytes,7,opt,name=r_hex,json=rHex,proto3" json:"r_hex,omitempty"`
	SHex                 string                 `protobuf:"bytes,8,opt,name=s_hex,json=sHex,proto3" json:"s_hex,omitempty"`
	SignedInputHex       string                 `protobuf:"bytes,9,opt,name=signed_input_hex,json=signedInputHex,proto3" json:"signed_input_hex,omitempty"`
	ErrorCode            string                 `protobuf:"bytes,10,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EcdsaPubkey          string                 `protobuf:"bytes,12,opt,name=ecdsa_pubkey,json=ecdsaPubkey,proto3" json:"ecdsa_pubkey,omitempty"`
	EddsaPubkey          string                 `protobuf:"bytes,13,opt,name=eddsa_pubkey,json=eddsaPubkey,proto3" json:"eddsa_pubkey,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SessionResult) Reset() {
	*x = SessionResult{}
	mi := &file_coordinator_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResult) ProtoMessage() {}

func (x *SessionResult) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResult.ProtoReflect.Descriptor instead.
func (*SessionResult) Descriptor() ([]byte, []int) {
	return file_coordinator_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *SessionResult) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *SessionResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResult) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SessionResult) GetPublicKeyHex() string {
	if x != nil {
		return x.PublicKeyHex
	}
	return ""
}

func (x *SessionResult) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

func (x *SessionResult) GetSignatureRecoveryHex() string {
	if x != nil {
		return x.SignatureRecoveryHex
	}
	return ""
}

func (x *SessionResult) GetRHex() string {
	if x != nil {
		return x.RHex
	}
	return ""
}

func (x *SessionResult) GetSHex() string {
	if x != nil {
		return x.SHex
	}
	return ""
}

func (x *SessionResult) GetSignedInputHex() string {
	if x != nil {
		return x.SignedInputHex
	}
	return ""
}

func (x *SessionResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SessionResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SessionResult) GetEcdsaPubkey() string {
	if x != nil {
		return x.EcdsaPubkey
	}
	return ""
}

func (x *SessionResult) GetEddsaPubkey() string {
	if x != nil {
		return x.EddsaPubkey
	}
	return ""
}

var File_coordinator_orchestration_proto protoreflect.FileDescriptor

const file_coordinator_orchestration_proto_rawDesc = "" +
	"\n" +
	"\x1fcoordinator_orchestration.proto\x12\x0ecoordinator.v1\"T\n" +
	"\vParticipant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x17identity_public_key_hex\x18\x02 \x01(\tR\x14identityPublicKeyHex\"\xa7\x01\n" +
	"\rKeygenRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\rR\tthreshold\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12?\n" +
	"\fparticipants\x18\x04 \x03(\v2\x1b.coordinator.v1.ParticipantR\fparticipants\"\xac\x02\n" +
	"\vSignRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\rR\tthreshold\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12*\n" +
	"\x11signing_input_hex\x18\x04 \x01(\tR\x0fsigningInputHex\x12?\n" +
	"\fparticipants\x18\x05 \x03(\v2\x1b.coordinator.v1.ParticipantR\fparticipants\x12'\n" +
	"\x0fderivation_path\x18\x06 \x03(\rR\x0ederivationPath\x120\n" +
	"\x14derivation_delta_hex\x18\a \x01(\tR\x12derivationDeltaHex\".\n" +
	"\rSessionLookup\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xaf\x01\n" +
	"\x0fRequestAccepted\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xc2\x03\n" +
	"\rSessionResult\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12$\n" +
	"\x0epublic_key_hex\x18\x04 \x01(\tR\fpublicKeyHex\x12#\n" +
	"\rsignature_hex\x18\x05 \x01(\tR\fsignatureHex\x124\n" +
	"\x16signature_recovery_hex\x18\x06 \x01(\tR\x14signatureRecoveryHex\x12\x13\n" +
	"\x05r_hex\x18\a \x01(\tR\x04rHex\x12\x13\n" +
	"\x05s_hex\x18\b \x01(\tR\x04sHex\x12(\n" +
	"\x10signed_input_hex\x18\t \x01(\tR\x0esignedInputHex\x12\x1d\n" +
	"\n" +
	"error_code\x18\n" +
	" \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12!\n" +
	"\fecdsa_pubkey\x18\f \x01(\tR\vecdsaPubkey\x12!\n" +
	"\feddsa_pubkey\x18\r \x01(\tR\veddsaPubkey2\xfd\x01\n" +
	"\x18CoordinatorOrchestration\x12H\n" +
	"\x06Keygen\x12\x1d.coordinator.v1.KeygenRequest\x1a\x1f.coordinator.v1.RequestAccepted\x12D\n" +
	"\x04Sign\x12\x1b.coordinator.v1.SignRequest\x1a\x1f.coordinator.v1.RequestAccepted\x12Q\n" +
	"\x11WaitSessionResult\x12\x1d.coordinator.v1.SessionLookup\x1a\x1d.coordinator.v1.SessionResultB`Z^github.com/fystack/mpcium-sdk/integrations/coordinator-grpc/proto/coordinator/v1;coordinatorv1b\x06proto3"

var (
	file_coordinator_orchestration_proto_rawDescOnce sync.Once
	file_coordinator_orchestration_proto_rawDescData []byte
)

func file_coordinator_orchestration_proto_rawDescGZIP() []byte {
	file_coordinator_orchestration_proto_rawDescOnce.Do(func() {
		file_coordinator_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_orchestration_proto_rawDesc), len(file_coordinator_orchestration_proto_rawDesc)))
	})
	return file_coordinator_orchestration_proto_rawDescData
}

var file_coordinator_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_coordinator_orchestration_proto_goTypes = []any{
	(*Participant)(nil),     // 0: coordinator.v1.Participant
	(*KeygenRequest)(nil),   // 1: coordinator.v1.KeygenRequest
	(*SignRequest)(nil),     // 2: coordinator.v1.SignRequest
	(*SessionLookup)(nil),   // 3: coordinator.v1.SessionLookup
	(*RequestAccepted)(nil), // 4: coordinator.v1.RequestAccepted
	(*SessionResult)(nil),   // 5: coordinator.v1.SessionResult
}
var file_coordinator_orchestration_proto_depIdxs = []int32{
	0, // 0: coordinator.v1.KeygenRequest.participants:type_name -> coordinator.v1.Participant
	0, // 1: coordinator.v1.SignRequest.participants:type_name -> coordinator.v1.Participant
	1, // 2: coordinator.v1.CoordinatorOrchestration.Keygen:input_type -> coordinator.v1.KeygenRequest
	2, // 3: coordinator.v1.CoordinatorOrchestration.Sign:input_type -> coordinator.v1.SignRequest
	3, // 4: coordinator.v1.CoordinatorOrchestration.WaitSessionResult:input_type -> coordinator.v1.SessionLookup
	4, // 5: coordinator.v1.CoordinatorOrchestration.Keygen:output_type -> coordinator.v1.RequestAccepted
	4, // 6: coordinator.v1.CoordinatorOrchestration.Sign:output_type -> coordinator.v1.RequestAccepted
	5, // 7: coordinator.v1.CoordinatorOrchestration.WaitSessionResult:output_type -> coordinator.v1.SessionResult
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coordinator_orchestration_proto_init() }
func file_coordinator_orchestration_proto_init() {
	if File_coordinator_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_orchestration_proto_rawDesc), len(file_coordinator_orchestration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_orchestration_proto_goTypes,
		DependencyIndexes: file_coordinator_orchestration_proto_depIdxs,
		MessageInfos:      file_coordinator_orchestration_proto_msgTypes,
	}.Build()
	File_coordinator_orchestration_proto = out.File
	file_coordinator_orchestration_proto_goTypes = nil
	file_coordinator_orchestration_proto_depIdxs = nil
}
