// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: coordinator_orchestration.proto

package coordinatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorOrchestration_Keygen_FullMethodName            = "/coordinator.v1.CoordinatorOrchestration/Keygen"
	CoordinatorOrchestration_Sign_FullMethodName              = "/coordinator.v1.CoordinatorOrchestration/Sign"
	CoordinatorOrchestration_WaitSessionResult_FullMethodName = "/coordinator.v1.CoordinatorOrchestration/WaitSessionResult"
)

// CoordinatorOrchestrationClient is the client API for CoordinatorOrchestration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorOrchestrationClient interface {
	Keygen(ctx context.Context, in *KeygenRequest, opts ...grpc.CallOption) (*RequestAccepted, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*RequestAccepted, error)
	WaitSessionResult(ctx context.Context, in *SessionLookup, opts ...grpc.CallOption) (*SessionResult, error)
}

type coordinatorOrchestrationClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorOrchestrationClient(cc grpc.ClientConnInterface) CoordinatorOrchestrationClient {
	return &coordinatorOrchestrationClient{cc}
}

func (c *coordinatorOrchestrationClient) Keygen(ctx context.Context, in *KeygenRequest, opts ...grpc.CallOption) (*RequestAccepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAccepted)
	err := c.cc.Invoke(ctx, CoordinatorOrchestration_Keygen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorOrchestrationClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*RequestAccepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAccepted)
	err := c.cc.Invoke(ctx, CoordinatorOrchestration_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorOrchestrationClient) WaitSessionResult(ctx context.Context, in *SessionLookup, opts ...grpc.CallOption) (*SessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResult)
	err := c.cc.Invoke(ctx, CoordinatorOrchestration_WaitSessionResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorOrchestrationServer is the server API for CoordinatorOrchestration service.
// All implementations must embed UnimplementedCoordinatorOrchestrationServer
// for forward compatibility.
type CoordinatorOrchestrationServer interface {
	Keygen(context.Context, *KeygenRequest) (*RequestAccepted, error)
	Sign(context.Context, *SignRequest) (*RequestAccepted, error)
	WaitSessionResult(context.Context, *SessionLookup) (*SessionResult, error)
	mustEmbedUnimplementedCoordinatorOrchestrationServer()
}

// UnimplementedCoordinatorOrchestrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorOrchestrationServer struct{}

func (UnimplementedCoordinatorOrchestrationServer) Keygen(context.Context, *KeygenRequest) (*RequestAccepted, error) {
	return nil, status.Error(codes.Unimplemented, "method Keygen not implemented")
}
func (UnimplementedCoordinatorOrchestrationServer) Sign(context.Context, *SignRequest) (*RequestAccepted, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedCoordinatorOrchestrationServer) WaitSessionResult(context.Context, *SessionLookup) (*SessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitSessionResult not implemented")
}
func (UnimplementedCoordinatorOrchestrationServer) mustEmbedUnimplementedCoordinatorOrchestrationServer() {
}
func (UnimplementedCoordinatorOrchestrationServer) testEmbeddedByValue() {}

// UnsafeCoordinatorOrchestrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorOrchestrationServer will
// result in compilation errors.
type UnsafeCoordinatorOrchestrationServer interface {
	mustEmbedUnimplementedCoordinatorOrchestrationServer()
}

func RegisterCoordinatorOrchestrationServer(s grpc.ServiceRegistrar, srv CoordinatorOrchestrationServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorOrchestrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorOrchestration_ServiceDesc, srv)
}

func _CoordinatorOrchestration_Keygen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeygenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorOrchestrationServer).Keygen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorOrchestration_Keygen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorOrchestrationServer).Keygen(ctx, req.(*KeygenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorOrchestration_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorOrchestrationServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorOrchestration_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorOrchestrationServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorOrchestration_WaitSessionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionLookup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorOrchestrationServer).WaitSessionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorOrchestration_WaitSessionResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorOrchestrationServer).WaitSessionResult(ctx, req.(*SessionLookup))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorOrchestration_ServiceDesc is the grpc.ServiceDesc for CoordinatorOrchestration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorOrchestration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.v1.CoordinatorOrchestration",
	HandlerType: (*CoordinatorOrchestrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Keygen",
			Handler:    _CoordinatorOrchestration_Keygen_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _CoordinatorOrchestration_Sign_Handler,
		},
		{
			MethodName: "WaitSessionResult",
			Handler:    _CoordinatorOrchestration_WaitSessionResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator_orchestration.proto",
}
