// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/gateway/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CosignerGateway_Connect_FullMethodName = "/gateway.v1.CosignerGateway/Connect"
)

// CosignerGatewayClient is the client API for CosignerGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CosignerGatewayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CosignerEnvelope, GatewayEnvelope], error)
}

type cosignerGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewCosignerGatewayClient(cc grpc.ClientConnInterface) CosignerGatewayClient {
	return &cosignerGatewayClient{cc}
}

func (c *cosignerGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CosignerEnvelope, GatewayEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CosignerGateway_ServiceDesc.Streams[0], CosignerGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CosignerEnvelope, GatewayEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CosignerGateway_ConnectClient = grpc.BidiStreamingClient[CosignerEnvelope, GatewayEnvelope]

// CosignerGatewayServer is the server API for CosignerGateway service.
// All implementations must embed UnimplementedCosignerGatewayServer
// for forward compatibility.
type CosignerGatewayServer interface {
	Connect(grpc.BidiStreamingServer[CosignerEnvelope, GatewayEnvelope]) error
	mustEmbedUnimplementedCosignerGatewayServer()
}

// UnimplementedCosignerGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCosignerGatewayServer struct{}

func (UnimplementedCosignerGatewayServer) Connect(grpc.BidiStreamingServer[CosignerEnvelope, GatewayEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCosignerGatewayServer) mustEmbedUnimplementedCosignerGatewayServer() {}
func (UnimplementedCosignerGatewayServer) testEmbeddedByValue()                         {}

// UnsafeCosignerGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CosignerGatewayServer will
// result in compilation errors.
type UnsafeCosignerGatewayServer interface {
	mustEmbedUnimplementedCosignerGatewayServer()
}

func RegisterCosignerGatewayServer(s grpc.ServiceRegistrar, srv CosignerGatewayServer) {
	// If the following call panics, it indicates UnimplementedCosignerGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CosignerGateway_ServiceDesc, srv)
}

func _CosignerGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CosignerGatewayServer).Connect(&grpc.GenericServerStream[CosignerEnvelope, GatewayEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CosignerGateway_ConnectServer = grpc.BidiStreamingServer[CosignerEnvelope, GatewayEnvelope]

// CosignerGateway_ServiceDesc is the grpc.ServiceDesc for CosignerGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CosignerGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.CosignerGateway",
	HandlerType: (*CosignerGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _CosignerGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/gateway/v1/gateway.proto",
}

const (
	GatewayControl_DisconnectCosigner_FullMethodName = "/gateway.v1.GatewayControl/DisconnectCosigner"
)

// GatewayControlClient is the client API for GatewayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayControlClient interface {
	DisconnectCosigner(ctx context.Context, in *DisconnectCosignerRequest, opts ...grpc.CallOption) (*DisconnectCosignerResponse, error)
}

type gatewayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayControlClient(cc grpc.ClientConnInterface) GatewayControlClient {
	return &gatewayControlClient{cc}
}

func (c *gatewayControlClient) DisconnectCosigner(ctx context.Context, in *DisconnectCosignerRequest, opts ...grpc.CallOption) (*DisconnectCosignerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectCosignerResponse)
	err := c.cc.Invoke(ctx, GatewayControl_DisconnectCosigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayControlServer is the server API for GatewayControl service.
// All implementations must embed UnimplementedGatewayControlServer
// for forward compatibility.
type GatewayControlServer interface {
	DisconnectCosigner(context.Context, *DisconnectCosignerRequest) (*DisconnectCosignerResponse, error)
	mustEmbedUnimplementedGatewayControlServer()
}

// UnimplementedGatewayControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayControlServer struct{}

func (UnimplementedGatewayControlServer) DisconnectCosigner(context.Context, *DisconnectCosignerRequest) (*DisconnectCosignerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectCosigner not implemented")
}
func (UnimplementedGatewayControlServer) mustEmbedUnimplementedGatewayControlServer() {}
func (UnimplementedGatewayControlServer) testEmbeddedByValue()                        {}

// UnsafeGatewayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayControlServer will
// result in compilation errors.
type UnsafeGatewayControlServer interface {
	mustEmbedUnimplementedGatewayControlServer()
}

func RegisterGatewayControlServer(s grpc.ServiceRegistrar, srv GatewayControlServer) {
	// If the following call panics, it indicates UnimplementedGatewayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayControl_ServiceDesc, srv)
}

func _GatewayControl_DisconnectCosigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectCosignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).DisconnectCosigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_DisconnectCosigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).DisconnectCosigner(ctx, req.(*DisconnectCosignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayControl_ServiceDesc is the grpc.ServiceDesc for GatewayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.GatewayControl",
	HandlerType: (*GatewayControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisconnectCosigner",
			Handler:    _GatewayControl_DisconnectCosigner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/gateway/v1/gateway.proto",
}
