// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvelopeKind int32

const (
	EnvelopeKind_ENVELOPE_KIND_UNSPECIFIED   EnvelopeKind = 0
	EnvelopeKind_ENVELOPE_KIND_CONTROL       EnvelopeKind = 1
	EnvelopeKind_ENVELOPE_KIND_P2P           EnvelopeKind = 2
	EnvelopeKind_ENVELOPE_KIND_SESSION_EVENT EnvelopeKind = 3
	EnvelopeKind_ENVELOPE_KIND_PRESENCE      EnvelopeKind = 4
)

// Enum value maps for EnvelopeKind.
var (
	EnvelopeKind_name = map[int32]string{
		0: "ENVELOPE_KIND_UNSPECIFIED",
		1: "ENVELOPE_KIND_CONTROL",
		2: "ENVELOPE_KIND_P2P",
		3: "ENVELOPE_KIND_SESSION_EVENT",
		4: "ENVELOPE_KIND_PRESENCE",
	}
	EnvelopeKind_value = map[string]int32{
		"ENVELOPE_KIND_UNSPECIFIED":   0,
		"ENVELOPE_KIND_CONTROL":       1,
		"ENVELOPE_KIND_P2P":           2,
		"ENVELOPE_KIND_SESSION_EVENT": 3,
		"ENVELOPE_KIND_PRESENCE":      4,
	}
)

func (x EnvelopeKind) Enum() *EnvelopeKind {
	p := new(EnvelopeKind)
	*p = x
	return p
}

func (x EnvelopeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (EnvelopeKind) Type() protoreflect.EnumType {
	return &file_api_gateway_v1_gateway_proto_enumTypes[0]
}

func (x EnvelopeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeKind.Descriptor instead.
func (EnvelopeKind) EnumDescriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type CosignerEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EnvelopeKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=gateway.v1.EnvelopeKind" json:"kind,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CosignerId    string                 `protobuf:"bytes,3,opt,name=cosigner_id,json=cosignerId,proto3" json:"cosigner_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,4,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosignerEnvelope) Reset() {
	*x = CosignerEnvelope{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosignerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosignerEnvelope) ProtoMessage() {}

func (x *CosignerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosignerEnvelope.ProtoReflect.Descriptor instead.
func (*CosignerEnvelope) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CosignerEnvelope) GetKind() EnvelopeKind {
	if x != nil {
		return x.Kind
	}
	return EnvelopeKind_ENVELOPE_KIND_UNSPECIFIED
}

func (x *CosignerEnvelope) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CosignerEnvelope) GetCosignerId() string {
	if x != nil {
		return x.CosignerId
	}
	return ""
}

func (x *CosignerEnvelope) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *CosignerEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CosignerEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GatewayEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EnvelopeKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=gateway.v1.EnvelopeKind" json:"kind,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CosignerId    string                 `protobuf:"bytes,3,opt,name=cosigner_id,json=cosignerId,proto3" json:"cosigner_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,4,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayEnvelope) Reset() {
	*x = GatewayEnvelope{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayEnvelope) ProtoMessage() {}

func (x *GatewayEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayEnvelope.ProtoReflect.Descriptor instead.
func (*GatewayEnvelope) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayEnvelope) GetKind() EnvelopeKind {
	if x != nil {
		return x.Kind
	}
	return EnvelopeKind_ENVELOPE_KIND_UNSPECIFIED
}

func (x *GatewayEnvelope) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GatewayEnvelope) GetCosignerId() string {
	if x != nil {
		return x.CosignerId
	}
	return ""
}

func (x *GatewayEnvelope) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *GatewayEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GatewayEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DisconnectCosignerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CosignerId    string                 `protobuf:"bytes,2,opt,name=cosigner_id,json=cosignerId,proto3" json:"cosigner_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectCosignerRequest) Reset() {
	*x = DisconnectCosignerRequest{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectCosignerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectCosignerRequest) ProtoMessage() {}

func (x *DisconnectCosignerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectCosignerRequest.ProtoReflect.Descriptor instead.
func (*DisconnectCosignerRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectCosignerRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DisconnectCosignerRequest) GetCosignerId() string {
	if x != nil {
		return x.CosignerId
	}
	return ""
}

func (x *DisconnectCosignerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DisconnectCosignerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disconnected  bool                   `protobuf:"varint,1,opt,name=disconnected,proto3" json:"disconnected,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectCosignerResponse) Reset() {
	*x = DisconnectCosignerResponse{}
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectCosignerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectCosignerResponse) ProtoMessage() {}

func (x *DisconnectCosignerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectCosignerResponse.ProtoReflect.Descriptor instead.
func (*DisconnectCosignerResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectCosignerResponse) GetDisconnected() bool {
	if x != nil {
		return x.Disconnected
	}
	return false
}

func (x *DisconnectCosignerResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

var File_api_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_api_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1capi/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"\xe4\x01\n" +
	"\x10CosignerEnvelope\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.gateway.v1.EnvelopeKindR\x04kind\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vcosigner_id\x18\x03 \x01(\tR\n" +
	"cosignerId\x12%\n" +
	"\x0eparticipant_id\x18\x04 \x01(\tR\rparticipantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\xe3\x01\n" +
	"\x0fGatewayEnvelope\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.gateway.v1.EnvelopeKindR\x04kind\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vcosigner_id\x18\x03 \x01(\tR\n" +
	"cosignerId\x12%\n" +
	"\x0eparticipant_id\x18\x04 \x01(\tR\rparticipantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"w\n" +
	"\x19DisconnectCosignerRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vcosigner_id\x18\x02 \x01(\tR\n" +
	"cosignerId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"g\n" +
	"\x1aDisconnectCosignerResponse\x12\"\n" +
	"\fdisconnected\x18\x01 \x01(\bR\fdisconnected\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId*\x9c\x01\n" +
	"\fEnvelopeKind\x12\x1d\n" +
	"\x19ENVELOPE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENVELOPE_KIND_CONTROL\x10\x01\x12\x15\n" +
	"\x11ENVELOPE_KIND_P2P\x10\x02\x12\x1f\n" +
	"\x1bENVELOPE_KIND_SESSION_EVENT\x10\x03\x12\x1a\n" +
	"\x16ENVELOPE_KIND_PRESENCE\x10\x042[\n" +
	"\x0fCosignerGateway\x12H\n" +
	"\aConnect\x12\x1c.gateway.v1.CosignerEnvelope\x1a\x1b.gateway.v1.GatewayEnvelope(\x010\x012u\n" +
	"\x0eGatewayControl\x12c\n" +
	"\x12DisconnectCosigner\x12%.gateway.v1.DisconnectCosignerRequest\x1a&.gateway.v1.DisconnectCosignerResponseB8Z6github.com/fystack/mpcium-sdk/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_api_gateway_v1_gateway_proto_rawDescData []byte
)

func file_api_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_api_gateway_v1_gateway_proto_rawDescData
}

var file_api_gateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_gateway_v1_gateway_proto_goTypes = []any{
	(EnvelopeKind)(0),                  // 0: gateway.v1.EnvelopeKind
	(*CosignerEnvelope)(nil),           // 1: gateway.v1.CosignerEnvelope
	(*GatewayEnvelope)(nil),            // 2: gateway.v1.GatewayEnvelope
	(*DisconnectCosignerRequest)(nil),  // 3: gateway.v1.DisconnectCosignerRequest
	(*DisconnectCosignerResponse)(nil), // 4: gateway.v1.DisconnectCosignerResponse
}
var file_api_gateway_v1_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.v1.CosignerEnvelope.kind:type_name -> gateway.v1.EnvelopeKind
	0, // 1: gateway.v1.GatewayEnvelope.kind:type_name -> gateway.v1.EnvelopeKind
	1, // 2: gateway.v1.CosignerGateway.Connect:input_type -> gateway.v1.CosignerEnvelope
	3, // 3: gateway.v1.GatewayControl.DisconnectCosigner:input_type -> gateway.v1.DisconnectCosignerRequest
	2, // 4: gateway.v1.CosignerGateway.Connect:output_type -> gateway.v1.GatewayEnvelope
	4, // 5: gateway.v1.GatewayControl.DisconnectCosigner:output_type -> gateway.v1.DisconnectCosignerResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_gateway_proto_init() }
func file_api_gateway_v1_gateway_proto_init() {
	if File_api_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_gateway_proto_rawDesc), len(file_api_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_api_gateway_v1_gateway_proto_enumTypes,
		MessageInfos:      file_api_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_gateway_proto = out.File
	file_api_gateway_v1_gateway_proto_goTypes = nil
	file_api_gateway_v1_gateway_proto_depIdxs = nil
}
