// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mpcium/v1/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolType int32

const (
	ProtocolType_PROTOCOL_TYPE_UNSPECIFIED ProtocolType = 0
	ProtocolType_PROTOCOL_TYPE_ECDSA       ProtocolType = 1
	ProtocolType_PROTOCOL_TYPE_EDDSA       ProtocolType = 2
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "PROTOCOL_TYPE_UNSPECIFIED",
		1: "PROTOCOL_TYPE_ECDSA",
		2: "PROTOCOL_TYPE_EDDSA",
	}
	ProtocolType_value = map[string]int32{
		"PROTOCOL_TYPE_UNSPECIFIED": 0,
		"PROTOCOL_TYPE_ECDSA":       1,
		"PROTOCOL_TYPE_EDDSA":       2,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_mpcium_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_mpcium_v1_protocol_proto_enumTypes[0]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{0}
}

type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_KEYGEN      OperationType = 1
	OperationType_OPERATION_TYPE_SIGN        OperationType = 2
	OperationType_OPERATION_TYPE_RESHARE     OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_KEYGEN",
		2: "OPERATION_TYPE_SIGN",
		3: "OPERATION_TYPE_RESHARE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_KEYGEN":      1,
		"OPERATION_TYPE_SIGN":        2,
		"OPERATION_TYPE_RESHARE":     3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_mpcium_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_mpcium_v1_protocol_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{1}
}

type ParticipantPhase int32

const (
	ParticipantPhase_PARTICIPANT_PHASE_UNSPECIFIED       ParticipantPhase = 0
	ParticipantPhase_PARTICIPANT_PHASE_CREATED           ParticipantPhase = 1
	ParticipantPhase_PARTICIPANT_PHASE_JOINING           ParticipantPhase = 2
	ParticipantPhase_PARTICIPANT_PHASE_READY             ParticipantPhase = 3
	ParticipantPhase_PARTICIPANT_PHASE_KEY_EXCHANGE      ParticipantPhase = 4
	ParticipantPhase_PARTICIPANT_PHASE_KEY_EXCHANGE_DONE ParticipantPhase = 5
	ParticipantPhase_PARTICIPANT_PHASE_MPC_RUNNING       ParticipantPhase = 6
	ParticipantPhase_PARTICIPANT_PHASE_COMPLETED         ParticipantPhase = 7
	ParticipantPhase_PARTICIPANT_PHASE_FAILED            ParticipantPhase = 8
	ParticipantPhase_PARTICIPANT_PHASE_ABORTED           ParticipantPhase = 9
)

// Enum value maps for ParticipantPhase.
var (
	ParticipantPhase_name = map[int32]string{
		0: "PARTICIPANT_PHASE_UNSPECIFIED",
		1: "PARTICIPANT_PHASE_CREATED",
		2: "PARTICIPANT_PHASE_JOINING",
		3: "PARTICIPANT_PHASE_READY",
		4: "PARTICIPANT_PHASE_KEY_EXCHANGE",
		5: "PARTICIPANT_PHASE_KEY_EXCHANGE_DONE",
		6: "PARTICIPANT_PHASE_MPC_RUNNING",
		7: "PARTICIPANT_PHASE_COMPLETED",
		8: "PARTICIPANT_PHASE_FAILED",
		9: "PARTICIPANT_PHASE_ABORTED",
	}
	ParticipantPhase_value = map[string]int32{
		"PARTICIPANT_PHASE_UNSPECIFIED":       0,
		"PARTICIPANT_PHASE_CREATED":           1,
		"PARTICIPANT_PHASE_JOINING":           2,
		"PARTICIPANT_PHASE_READY":             3,
		"PARTICIPANT_PHASE_KEY_EXCHANGE":      4,
		"PARTICIPANT_PHASE_KEY_EXCHANGE_DONE": 5,
		"PARTICIPANT_PHASE_MPC_RUNNING":       6,
		"PARTICIPANT_PHASE_COMPLETED":         7,
		"PARTICIPANT_PHASE_FAILED":            8,
		"PARTICIPANT_PHASE_ABORTED":           9,
	}
)

func (x ParticipantPhase) Enum() *ParticipantPhase {
	p := new(ParticipantPhase)
	*p = x
	return p
}

func (x ParticipantPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_mpcium_v1_protocol_proto_enumTypes[2].Descriptor()
}

func (ParticipantPhase) Type() protoreflect.EnumType {
	return &file_mpcium_v1_protocol_proto_enumTypes[2]
}

func (x ParticipantPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantPhase.Descriptor instead.
func (ParticipantPhase) EnumDescriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{2}
}

type FailureReason int32

const (
	FailureReason_FAILURE_REASON_UNSPECIFIED           FailureReason = 0
	FailureReason_FAILURE_REASON_INVALID_SESSION       FailureReason = 1
	FailureReason_FAILURE_REASON_INVALID_MESSAGE       FailureReason = 2
	FailureReason_FAILURE_REASON_INVALID_SIGNATURE     FailureReason = 3
	FailureReason_FAILURE_REASON_DECRYPT_FAILED        FailureReason = 4
	FailureReason_FAILURE_REASON_UNSUPPORTED_OPERATION FailureReason = 5
	FailureReason_FAILURE_REASON_MISSING_PREREQUISITE  FailureReason = 6
	FailureReason_FAILURE_REASON_TSS_ERROR             FailureReason = 7
	FailureReason_FAILURE_REASON_ABORTED               FailureReason = 8
	FailureReason_FAILURE_REASON_TIMEOUT               FailureReason = 9
	FailureReason_FAILURE_REASON_REPLAY                FailureReason = 10
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0:  "FAILURE_REASON_UNSPECIFIED",
		1:  "FAILURE_REASON_INVALID_SESSION",
		2:  "FAILURE_REASON_INVALID_MESSAGE",
		3:  "FAILURE_REASON_INVALID_SIGNATURE",
		4:  "FAILURE_REASON_DECRYPT_FAILED",
		5:  "FAILURE_REASON_UNSUPPORTED_OPERATION",
		6:  "FAILURE_REASON_MISSING_PREREQUISITE",
		7:  "FAILURE_REASON_TSS_ERROR",
		8:  "FAILURE_REASON_ABORTED",
		9:  "FAILURE_REASON_TIMEOUT",
		10: "FAILURE_REASON_REPLAY",
	}
	FailureReason_value = map[string]int32{
		"FAILURE_REASON_UNSPECIFIED":           0,
		"FAILURE_REASON_INVALID_SESSION":       1,
		"FAILURE_REASON_INVALID_MESSAGE":       2,
		"FAILURE_REASON_INVALID_SIGNATURE":     3,
		"FAILURE_REASON_DECRYPT_FAILED":        4,
		"FAILURE_REASON_UNSUPPORTED_OPERATION": 5,
		"FAILURE_REASON_MISSING_PREREQUISITE":  6,
		"FAILURE_REASON_TSS_ERROR":             7,
		"FAILURE_REASON_ABORTED":               8,
		"FAILURE_REASON_TIMEOUT":               9,
		"FAILURE_REASON_REPLAY":                10,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_mpcium_v1_protocol_proto_enumTypes[3].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_mpcium_v1_protocol_proto_enumTypes[3]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{3}
}

type SessionParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	PartyKey      []byte                 `protobuf:"bytes,2,opt,name=party_key,json=partyKey,proto3" json:"party_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionParticipant) Reset() {
	*x = SessionParticipant{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionParticipant) ProtoMessage() {}

func (x *SessionParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionParticipant.ProtoReflect.Descriptor instead.
func (*SessionParticipant) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *SessionParticipant) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *SessionParticipant) GetPartyKey() []byte {
	if x != nil {
		return x.PartyKey
	}
	return nil
}

type NonHardenedDerivation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []uint32               `protobuf:"varint,1,rep,packed,name=path,proto3" json:"path,omitempty"`
	Delta         []byte                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonHardenedDerivation) Reset() {
	*x = NonHardenedDerivation{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonHardenedDerivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonHardenedDerivation) ProtoMessage() {}

func (x *NonHardenedDerivation) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonHardenedDerivation.ProtoReflect.Descriptor instead.
func (*NonHardenedDerivation) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *NonHardenedDerivation) GetPath() []uint32 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *NonHardenedDerivation) GetDelta() []byte {
	if x != nil {
		return x.Delta
	}
	return nil
}

type KeygenPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenPayload) Reset() {
	*x = KeygenPayload{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenPayload) ProtoMessage() {}

func (x *KeygenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenPayload.ProtoReflect.Descriptor instead.
func (*KeygenPayload) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *KeygenPayload) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type SignPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	SigningInput  []byte                 `protobuf:"bytes,2,opt,name=signing_input,json=signingInput,proto3" json:"signing_input,omitempty"`
	Derivation    *NonHardenedDerivation `protobuf:"bytes,3,opt,name=derivation,proto3" json:"derivation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignPayload) Reset() {
	*x = SignPayload{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignPayload) ProtoMessage() {}

func (x *SignPayload) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignPayload.ProtoReflect.Descriptor instead.
func (*SignPayload) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *SignPayload) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignPayload) GetSigningInput() []byte {
	if x != nil {
		return x.SigningInput
	}
	return nil
}

func (x *SignPayload) GetDerivation() *NonHardenedDerivation {
	if x != nil {
		return x.Derivation
	}
	return nil
}

type ResharePayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyId           string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NewThreshold    uint32                 `protobuf:"varint,2,opt,name=new_threshold,json=newThreshold,proto3" json:"new_threshold,omitempty"`
	NewParticipants []*SessionParticipant  `protobuf:"bytes,3,rep,name=new_participants,json=newParticipants,proto3" json:"new_participants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResharePayload) Reset() {
	*x = ResharePayload{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResharePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResharePayload) ProtoMessage() {}

func (x *ResharePayload) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResharePayload.ProtoReflect.Descriptor instead.
func (*ResharePayload) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ResharePayload) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ResharePayload) GetNewThreshold() uint32 {
	if x != nil {
		return x.NewThreshold
	}
	return 0
}

func (x *ResharePayload) GetNewParticipants() []*SessionParticipant {
	if x != nil {
		return x.NewParticipants
	}
	return nil
}

type SessionStart struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SessionId    string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Protocol     ProtocolType           `protobuf:"varint,2,opt,name=protocol,proto3,enum=mpcium.protocol.v1.ProtocolType" json:"protocol,omitempty"`
	Operation    OperationType          `protobuf:"varint,3,opt,name=operation,proto3,enum=mpcium.protocol.v1.OperationType" json:"operation,omitempty"`
	Threshold    uint32                 `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Participants []*SessionParticipant  `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SessionStart_Keygen
	//	*SessionStart_Sign
	//	*SessionStart_Reshare
	Payload       isSessionStart_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *SessionStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStart) GetProtocol() ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

func (x *SessionStart) GetOperation() OperationType {
	if x != nil {
		return x.Operation
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *SessionStart) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SessionStart) GetParticipants() []*SessionParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *SessionStart) GetPayload() isSessionStart_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SessionStart) GetKeygen() *KeygenPayload {
	if x != nil {
		if x, ok := x.Payload.(*SessionStart_Keygen); ok {
			return x.Keygen
		}
	}
	return nil
}

func (x *SessionStart) GetSign() *SignPayload {
	if x != nil {
		if x, ok := x.Payload.(*SessionStart_Sign); ok {
			return x.Sign
		}
	}
	return nil
}

func (x *SessionStart) GetReshare() *ResharePayload {
	if x != nil {
		if x, ok := x.Payload.(*SessionStart_Reshare); ok {
			return x.Reshare
		}
	}
	return nil
}

type isSessionStart_Payload interface {
	isSessionStart_Payload()
}

type SessionStart_Keygen struct {
	Keygen *KeygenPayload `protobuf:"bytes,10,opt,name=keygen,proto3,oneof"`
}

type SessionStart_Sign struct {
	Sign *SignPayload `protobuf:"bytes,11,opt,name=sign,proto3,oneof"`
}

type SessionStart_Reshare struct {
	Reshare *ResharePayload `protobuf:"bytes,12,opt,name=reshare,proto3,oneof"`
}

func (*SessionStart_Keygen) isSessionStart_Payload() {}

func (*SessionStart_Sign) isSessionStart_Payload() {}

func (*SessionStart_Reshare) isSessionStart_Payload() {}

type KeyExchangeBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyExchangeBegin) Reset() {
	*x = KeyExchangeBegin{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeBegin) ProtoMessage() {}

func (x *KeyExchangeBegin) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeBegin.ProtoReflect.Descriptor instead.
func (*KeyExchangeBegin) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{6}
}

type MpcBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpcBegin) Reset() {
	*x = MpcBegin{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpcBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpcBegin) ProtoMessage() {}

func (x *MpcBegin) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpcBegin.ProtoReflect.Descriptor instead.
func (*MpcBegin) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{7}
}

type SessionAbort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        FailureReason          `protobuf:"varint,1,opt,name=reason,proto3,enum=mpcium.protocol.v1.FailureReason" json:"reason,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAbort) Reset() {
	*x = SessionAbort{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAbort) ProtoMessage() {}

func (x *SessionAbort) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAbort.ProtoReflect.Descriptor instead.
func (*SessionAbort) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *SessionAbort) GetReason() FailureReason {
	if x != nil {
		return x.Reason
	}
	return FailureReason_FAILURE_REASON_UNSPECIFIED
}

func (x *SessionAbort) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,3,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControlMessage_SessionStart
	//	*ControlMessage_KeyExchangeBegin
	//	*ControlMessage_MpcBegin
	//	*ControlMessage_SessionAbort
	Body          isControlMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *ControlMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControlMessage) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *ControlMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ControlMessage) GetBody() isControlMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlMessage) GetSessionStart() *SessionStart {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_SessionStart); ok {
			return x.SessionStart
		}
	}
	return nil
}

func (x *ControlMessage) GetKeyExchangeBegin() *KeyExchangeBegin {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_KeyExchangeBegin); ok {
			return x.KeyExchangeBegin
		}
	}
	return nil
}

func (x *ControlMessage) GetMpcBegin() *MpcBegin {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_MpcBegin); ok {
			return x.MpcBegin
		}
	}
	return nil
}

func (x *ControlMessage) GetSessionAbort() *SessionAbort {
	if x != nil {
		if x, ok := x.Body.(*ControlMessage_SessionAbort); ok {
			return x.SessionAbort
		}
	}
	return nil
}

type isControlMessage_Body interface {
	isControlMessage_Body()
}

type ControlMessage_SessionStart struct {
	SessionStart *SessionStart `protobuf:"bytes,10,opt,name=session_start,json=sessionStart,proto3,oneof"`
}

type ControlMessage_KeyExchangeBegin struct {
	KeyExchangeBegin *KeyExchangeBegin `protobuf:"bytes,11,opt,name=key_exchange_begin,json=keyExchangeBegin,proto3,oneof"`
}

type ControlMessage_MpcBegin struct {
	MpcBegin *MpcBegin `protobuf:"bytes,12,opt,name=mpc_begin,json=mpcBegin,proto3,oneof"`
}

type ControlMessage_SessionAbort struct {
	SessionAbort *SessionAbort `protobuf:"bytes,13,opt,name=session_abort,json=sessionAbort,proto3,oneof"`
}

func (*ControlMessage_SessionStart) isControlMessage_Body() {}

func (*ControlMessage_KeyExchangeBegin) isControlMessage_Body() {}

func (*ControlMessage_MpcBegin) isControlMessage_Body() {}

func (*ControlMessage_SessionAbort) isControlMessage_Body() {}

type KeyExchangeHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	X25519PublicKey []byte                 `protobuf:"bytes,1,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeyExchangeHello) Reset() {
	*x = KeyExchangeHello{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeHello) ProtoMessage() {}

func (x *KeyExchangeHello) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeHello.ProtoReflect.Descriptor instead.
func (*KeyExchangeHello) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *KeyExchangeHello) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

type MpcPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpcPacket) Reset() {
	*x = MpcPacket{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpcPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpcPacket) ProtoMessage() {}

func (x *MpcPacket) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpcPacket.ProtoReflect.Descriptor instead.
func (*MpcPacket) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *MpcPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MpcPacket) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type PeerMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence          uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	FromParticipantId string                 `protobuf:"bytes,3,opt,name=from_participant_id,json=fromParticipantId,proto3" json:"from_participant_id,omitempty"`
	ToParticipantId   string                 `protobuf:"bytes,4,opt,name=to_participant_id,json=toParticipantId,proto3" json:"to_participant_id,omitempty"`
	Broadcast         bool                   `protobuf:"varint,5,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Phase             ParticipantPhase       `protobuf:"varint,6,opt,name=phase,proto3,enum=mpcium.protocol.v1.ParticipantPhase" json:"phase,omitempty"`
	Signature         []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*PeerMessage_KeyExchangeHello
	//	*PeerMessage_MpcPacket
	Body          isPeerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage) Reset() {
	*x = PeerMessage{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage) ProtoMessage() {}

func (x *PeerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage.ProtoReflect.Descriptor instead.
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *PeerMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PeerMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PeerMessage) GetFromParticipantId() string {
	if x != nil {
		return x.FromParticipantId
	}
	return ""
}

func (x *PeerMessage) GetToParticipantId() string {
	if x != nil {
		return x.ToParticipantId
	}
	return ""
}

func (x *PeerMessage) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *PeerMessage) GetPhase() ParticipantPhase {
	if x != nil {
		return x.Phase
	}
	return ParticipantPhase_PARTICIPANT_PHASE_UNSPECIFIED
}

func (x *PeerMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PeerMessage) GetBody() isPeerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PeerMessage) GetKeyExchangeHello() *KeyExchangeHello {
	if x != nil {
		if x, ok := x.Body.(*PeerMessage_KeyExchangeHello); ok {
			return x.KeyExchangeHello
		}
	}
	return nil
}

func (x *PeerMessage) GetMpcPacket() *MpcPacket {
	if x != nil {
		if x, ok := x.Body.(*PeerMessage_MpcPacket); ok {
			return x.MpcPacket
		}
	}
	return nil
}

type isPeerMessage_Body interface {
	isPeerMessage_Body()
}

type PeerMessage_KeyExchangeHello struct {
	KeyExchangeHello *KeyExchangeHello `protobuf:"bytes,10,opt,name=key_exchange_hello,json=keyExchangeHello,proto3,oneof"`
}

type PeerMessage_MpcPacket struct {
	MpcPacket *MpcPacket `protobuf:"bytes,11,opt,name=mpc_packet,json=mpcPacket,proto3,oneof"`
}

func (*PeerMessage_KeyExchangeHello) isPeerMessage_Body() {}

func (*PeerMessage_MpcPacket) isPeerMessage_Body() {}

type KeyShareResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ShareBlob     []byte                 `protobuf:"bytes,2,opt,name=share_blob,json=shareBlob,proto3" json:"share_blob,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyShareResult) Reset() {
	*x = KeyShareResult{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyShareResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyShareResult) ProtoMessage() {}

func (x *KeyShareResult) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyShareResult.ProtoReflect.Descriptor instead.
func (*KeyShareResult) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *KeyShareResult) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyShareResult) GetShareBlob() []byte {
	if x != nil {
		return x.ShareBlob
	}
	return nil
}

func (x *KeyShareResult) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SignatureResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	KeyId             string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Signature         []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SignatureRecovery []byte                 `protobuf:"bytes,3,opt,name=signature_recovery,json=signatureRecovery,proto3" json:"signature_recovery,omitempty"`
	R                 []byte                 `protobuf:"bytes,4,opt,name=r,proto3" json:"r,omitempty"`
	S                 []byte                 `protobuf:"bytes,5,opt,name=s,proto3" json:"s,omitempty"`
	SignedInput       []byte                 `protobuf:"bytes,6,opt,name=signed_input,json=signedInput,proto3" json:"signed_input,omitempty"`
	PublicKey         []byte                 `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignatureResult) Reset() {
	*x = SignatureResult{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureResult) ProtoMessage() {}

func (x *SignatureResult) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureResult.ProtoReflect.Descriptor instead.
func (*SignatureResult) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *SignatureResult) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignatureResult) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignatureResult) GetSignatureRecovery() []byte {
	if x != nil {
		return x.SignatureRecovery
	}
	return nil
}

func (x *SignatureResult) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SignatureResult) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *SignatureResult) GetSignedInput() []byte {
	if x != nil {
		return x.SignedInput
	}
	return nil
}

func (x *SignatureResult) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Result_KeyShare
	//	*Result_Signature
	Body          isResult_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *Result) GetBody() isResult_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Result) GetKeyShare() *KeyShareResult {
	if x != nil {
		if x, ok := x.Body.(*Result_KeyShare); ok {
			return x.KeyShare
		}
	}
	return nil
}

func (x *Result) GetSignature() *SignatureResult {
	if x != nil {
		if x, ok := x.Body.(*Result_Signature); ok {
			return x.Signature
		}
	}
	return nil
}

type isResult_Body interface {
	isResult_Body()
}

type Result_KeyShare struct {
	KeyShare *KeyShareResult `protobuf:"bytes,1,opt,name=key_share,json=keyShare,proto3,oneof"`
}

type Result_Signature struct {
	Signature *SignatureResult `protobuf:"bytes,2,opt,name=signature,proto3,oneof"`
}

func (*Result_KeyShare) isResult_Body() {}

func (*Result_Signature) isResult_Body() {}

type PeerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerJoined) Reset() {
	*x = PeerJoined{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerJoined) ProtoMessage() {}

func (x *PeerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerJoined.ProtoReflect.Descriptor instead.
func (*PeerJoined) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *PeerJoined) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type PeerReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerReady) Reset() {
	*x = PeerReady{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerReady) ProtoMessage() {}

func (x *PeerReady) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerReady.ProtoReflect.Descriptor instead.
func (*PeerReady) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *PeerReady) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type PeerKeyExchangeDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerKeyExchangeDone) Reset() {
	*x = PeerKeyExchangeDone{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerKeyExchangeDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerKeyExchangeDone) ProtoMessage() {}

func (x *PeerKeyExchangeDone) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerKeyExchangeDone.ProtoReflect.Descriptor instead.
func (*PeerKeyExchangeDone) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *PeerKeyExchangeDone) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type PeerFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Reason        FailureReason          `protobuf:"varint,2,opt,name=reason,proto3,enum=mpcium.protocol.v1.FailureReason" json:"reason,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerFailed) Reset() {
	*x = PeerFailed{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerFailed) ProtoMessage() {}

func (x *PeerFailed) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerFailed.ProtoReflect.Descriptor instead.
func (*PeerFailed) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *PeerFailed) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *PeerFailed) GetReason() FailureReason {
	if x != nil {
		return x.Reason
	}
	return FailureReason_FAILURE_REASON_UNSPECIFIED
}

func (x *PeerFailed) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type SessionCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCompleted) Reset() {
	*x = SessionCompleted{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCompleted) ProtoMessage() {}

func (x *SessionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCompleted.ProtoReflect.Descriptor instead.
func (*SessionCompleted) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *SessionCompleted) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type SessionFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        FailureReason          `protobuf:"varint,1,opt,name=reason,proto3,enum=mpcium.protocol.v1.FailureReason" json:"reason,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFailed) Reset() {
	*x = SessionFailed{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFailed) ProtoMessage() {}

func (x *SessionFailed) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFailed.ProtoReflect.Descriptor instead.
func (*SessionFailed) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{21}
}

func (x *SessionFailed) GetReason() FailureReason {
	if x != nil {
		return x.Reason
	}
	return FailureReason_FAILURE_REASON_UNSPECIFIED
}

func (x *SessionFailed) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*SessionEvent_PeerJoined
	//	*SessionEvent_PeerReady
	//	*SessionEvent_PeerKeyExchangeDone
	//	*SessionEvent_PeerFailed
	//	*SessionEvent_SessionCompleted
	//	*SessionEvent_SessionFailed
	Body          isSessionEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_mpcium_v1_protocol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mpcium_v1_protocol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_mpcium_v1_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *SessionEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SessionEvent) GetBody() isSessionEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SessionEvent) GetPeerJoined() *PeerJoined {
	if x != nil {
		if x, ok := x.Body.(*SessionEvent_PeerJoined); ok {
			return x.PeerJoined
		}
	}
	return nil
}

func (x *SessionEvent) GetPeerReady() *PeerReady {
	if x != nil {
		if x, ok := x.Body.(*SessionEvent_PeerReady); ok {
			return x.PeerReady
		}
	}
	return nil
}

func (x *SessionEvent) GetPeerKeyExchangeDone() *PeerKeyExchangeDone {
	if x != nil {
		if x, ok := x.Body.(*SessionEvent_PeerKeyExchangeDone); ok {
			return x.PeerKeyExchangeDone
		}
	}
	return nil
}

func (x *SessionEvent) GetPeerFailed() *PeerFailed {
	if x != nil {
		if x, ok := x.Body.(*SessionEvent_PeerFailed); ok {
			return x.PeerFailed
		}
	}
	return nil
}

func (x *SessionEvent) GetSessionCompleted() *SessionCompleted {
	if x != nil {
		if x, ok := x.Body.(*SessionEvent_SessionCompleted); ok {
			return x.SessionCompleted
		}
	}
	return nil
}

func (x *SessionEvent) GetSessionFailed() *SessionFailed {
	if x != nil {
		if x, ok := x.Body.(*SessionEvent_SessionFailed); ok {
			return x.SessionFailed
		}
	}
	return nil
}

type isSessionEvent_Body interface {
	isSessionEvent_Body()
}

type SessionEvent_PeerJoined struct {
	PeerJoined *PeerJoined `protobuf:"bytes,10,opt,name=peer_joined,json=peerJoined,proto3,oneof"`
}

type SessionEvent_PeerReady struct {
	PeerReady *PeerReady `protobuf:"bytes,11,opt,name=peer_ready,json=peerReady,proto3,oneof"`
}

type SessionEvent_PeerKeyExchangeDone struct {
	PeerKeyExchangeDone *PeerKeyExchangeDone `protobuf:"bytes,12,opt,name=peer_key_exchange_done,json=peerKeyExchangeDone,proto3,oneof"`
}

type SessionEvent_PeerFailed struct {
	PeerFailed *PeerFailed `protobuf:"bytes,13,opt,name=peer_failed,json=peerFailed,proto3,oneof"`
}

type SessionEvent_SessionCompleted struct {
	SessionCompleted *SessionCompleted `protobuf:"bytes,14,opt,name=session_completed,json=sessionCompleted,proto3,oneof"`
}

type SessionEvent_SessionFailed struct {
	SessionFailed *SessionFailed `protobuf:"bytes,15,opt,name=session_failed,json=sessionFailed,proto3,oneof"`
}

func (*SessionEvent_PeerJoined) isSessionEvent_Body() {}

func (*SessionEvent_PeerReady) isSessionEvent_Body() {}

func (*SessionEvent_PeerKeyExchangeDone) isSessionEvent_Body() {}

func (*SessionEvent_PeerFailed) isSessionEvent_Body() {}

func (*SessionEvent_SessionCompleted) isSessionEvent_Body() {}

func (*SessionEvent_SessionFailed) isSessionEvent_Body() {}

var File_mpcium_v1_protocol_proto protoreflect.FileDescriptor

const file_mpcium_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x18mpcium/v1/protocol.proto\x12\x12mpcium.protocol.v1\"X\n" +
	"\x12SessionParticipant\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x1b\n" +
	"\tparty_key\x18\x02 \x01(\fR\bpartyKey\"A\n" +
	"\x15NonHardenedDerivation\x12\x12\n" +
	"\x04path\x18\x01 \x03(\rR\x04path\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\fR\x05delta\"&\n" +
	"\rKeygenPayload\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"\x94\x01\n" +
	"\vSignPayload\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12#\n" +
	"\rsigning_input\x18\x02 \x01(\fR\fsigningInput\x12I\n" +
	"\n" +
	"derivation\x18\x03 \x01(\v2).mpcium.protocol.v1.NonHardenedDerivationR\n" +
	"derivation\"\x9f\x01\n" +
	"\x0eResharePayload\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12#\n" +
	"\rnew_threshold\x18\x02 \x01(\rR\fnewThreshold\x12Q\n" +
	"\x10new_participants\x18\x03 \x03(\v2&.mpcium.protocol.v1.SessionParticipantR\x0fnewParticipants\"\xd5\x03\n" +
	"\fSessionStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12<\n" +
	"\bprotocol\x18\x02 \x01(\x0e2 .mpcium.protocol.v1.ProtocolTypeR\bprotocol\x12?\n" +
	"\toperation\x18\x03 \x01(\x0e2!.mpcium.protocol.v1.OperationTypeR\toperation\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\rR\tthreshold\x12J\n" +
	"\fparticipants\x18\x05 \x03(\v2&.mpcium.protocol.v1.SessionParticipantR\fparticipants\x12;\n" +
	"\x06keygen\x18\n" +
	" \x01(\v2!.mpcium.protocol.v1.KeygenPayloadH\x00R\x06keygen\x125\n" +
	"\x04sign\x18\v \x01(\v2\x1f.mpcium.protocol.v1.SignPayloadH\x00R\x04sign\x12>\n" +
	"\areshare\x18\f \x01(\v2\".mpcium.protocol.v1.ResharePayloadH\x00R\areshareB\t\n" +
	"\apayload\"\x12\n" +
	"\x10KeyExchangeBegin\"\n" +
	"\n" +
	"\bMpcBegin\"a\n" +
	"\fSessionAbort\x129\n" +
	"\x06reason\x18\x01 \x01(\x0e2!.mpcium.protocol.v1.FailureReasonR\x06reason\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xbd\x03\n" +
	"\x0eControlMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12%\n" +
	"\x0ecoordinator_id\x18\x03 \x01(\tR\rcoordinatorId\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12G\n" +
	"\rsession_start\x18\n" +
	" \x01(\v2 .mpcium.protocol.v1.SessionStartH\x00R\fsessionStart\x12T\n" +
	"\x12key_exchange_begin\x18\v \x01(\v2$.mpcium.protocol.v1.KeyExchangeBeginH\x00R\x10keyExchangeBegin\x12;\n" +
	"\tmpc_begin\x18\f \x01(\v2\x1c.mpcium.protocol.v1.MpcBeginH\x00R\bmpcBegin\x12G\n" +
	"\rsession_abort\x18\r \x01(\v2 .mpcium.protocol.v1.SessionAbortH\x00R\fsessionAbortB\x06\n" +
	"\x04body\">\n" +
	"\x10KeyExchangeHello\x12*\n" +
	"\x11x25519_public_key\x18\x01 \x01(\fR\x0fx25519PublicKey\";\n" +
	"\tMpcPacket\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\"\xba\x03\n" +
	"\vPeerMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12.\n" +
	"\x13from_participant_id\x18\x03 \x01(\tR\x11fromParticipantId\x12*\n" +
	"\x11to_participant_id\x18\x04 \x01(\tR\x0ftoParticipantId\x12\x1c\n" +
	"\tbroadcast\x18\x05 \x01(\bR\tbroadcast\x12:\n" +
	"\x05phase\x18\x06 \x01(\x0e2$.mpcium.protocol.v1.ParticipantPhaseR\x05phase\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12T\n" +
	"\x12key_exchange_hello\x18\n" +
	" \x01(\v2$.mpcium.protocol.v1.KeyExchangeHelloH\x00R\x10keyExchangeHello\x12>\n" +
	"\n" +
	"mpc_packet\x18\v \x01(\v2\x1d.mpcium.protocol.v1.MpcPacketH\x00R\tmpcPacketB\x06\n" +
	"\x04body\"e\n" +
	"\x0eKeyShareResult\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"share_blob\x18\x02 \x01(\fR\tshareBlob\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"\xd3\x01\n" +
	"\x0fSignatureResult\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12-\n" +
	"\x12signature_recovery\x18\x03 \x01(\fR\x11signatureRecovery\x12\f\n" +
	"\x01r\x18\x04 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x05 \x01(\fR\x01s\x12!\n" +
	"\fsigned_input\x18\x06 \x01(\fR\vsignedInput\x12\x1d\n" +
	"\n" +
	"public_key\x18\a \x01(\fR\tpublicKey\"\x98\x01\n" +
	"\x06Result\x12A\n" +
	"\tkey_share\x18\x01 \x01(\v2\".mpcium.protocol.v1.KeyShareResultH\x00R\bkeyShare\x12C\n" +
	"\tsignature\x18\x02 \x01(\v2#.mpcium.protocol.v1.SignatureResultH\x00R\tsignatureB\x06\n" +
	"\x04body\"3\n" +
	"\n" +
	"PeerJoined\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\"2\n" +
	"\tPeerReady\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\"<\n" +
	"\x13PeerKeyExchangeDone\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\"\x86\x01\n" +
	"\n" +
	"PeerFailed\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x129\n" +
	"\x06reason\x18\x02 \x01(\x0e2!.mpcium.protocol.v1.FailureReasonR\x06reason\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"F\n" +
	"\x10SessionCompleted\x122\n" +
	"\x06result\x18\x01 \x01(\v2\x1a.mpcium.protocol.v1.ResultR\x06result\"b\n" +
	"\rSessionFailed\x129\n" +
	"\x06reason\x18\x01 \x01(\x0e2!.mpcium.protocol.v1.FailureReasonR\x06reason\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xbf\x04\n" +
	"\fSessionEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12A\n" +
	"\vpeer_joined\x18\n" +
	" \x01(\v2\x1e.mpcium.protocol.v1.PeerJoinedH\x00R\n" +
	"peerJoined\x12>\n" +
	"\n" +
	"peer_ready\x18\v \x01(\v2\x1d.mpcium.protocol.v1.PeerReadyH\x00R\tpeerReady\x12^\n" +
	"\x16peer_key_exchange_done\x18\f \x01(\v2'.mpcium.protocol.v1.PeerKeyExchangeDoneH\x00R\x13peerKeyExchangeDone\x12A\n" +
	"\vpeer_failed\x18\r \x01(\v2\x1e.mpcium.protocol.v1.PeerFailedH\x00R\n" +
	"peerFailed\x12S\n" +
	"\x11session_completed\x18\x0e \x01(\v2$.mpcium.protocol.v1.SessionCompletedH\x00R\x10sessionCompleted\x12J\n" +
	"\x0esession_failed\x18\x0f \x01(\v2!.mpcium.protocol.v1.SessionFailedH\x00R\rsessionFailedB\x06\n" +
	"\x04body*_\n" +
	"\fProtocolType\x12\x1d\n" +
	"\x19PROTOCOL_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PROTOCOL_TYPE_ECDSA\x10\x01\x12\x17\n" +
	"\x13PROTOCOL_TYPE_EDDSA\x10\x02*\x7f\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_TYPE_KEYGEN\x10\x01\x12\x17\n" +
	"\x13OPERATION_TYPE_SIGN\x10\x02\x12\x1a\n" +
	"\x16OPERATION_TYPE_RESHARE\x10\x03*\xde\x02\n" +
	"\x10ParticipantPhase\x12!\n" +
	"\x1dPARTICIPANT_PHASE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PARTICIPANT_PHASE_CREATED\x10\x01\x12\x1d\n" +
	"\x19PARTICIPANT_PHASE_JOINING\x10\x02\x12\x1b\n" +
	"\x17PARTICIPANT_PHASE_READY\x10\x03\x12\"\n" +
	"\x1ePARTICIPANT_PHASE_KEY_EXCHANGE\x10\x04\x12'\n" +
	"#PARTICIPANT_PHASE_KEY_EXCHANGE_DONE\x10\x05\x12!\n" +
	"\x1dPARTICIPANT_PHASE_MPC_RUNNING\x10\x06\x12\x1f\n" +
	"\x1bPARTICIPANT_PHASE_COMPLETED\x10\a\x12\x1c\n" +
	"\x18PARTICIPANT_PHASE_FAILED\x10\b\x12\x1d\n" +
	"\x19PARTICIPANT_PHASE_ABORTED\x10\t*\x84\x03\n" +
	"\rFailureReason\x12\x1e\n" +
	"\x1aFAILURE_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFAILURE_REASON_INVALID_SESSION\x10\x01\x12\"\n" +
	"\x1eFAILURE_REASON_INVALID_MESSAGE\x10\x02\x12$\n" +
	" FAILURE_REASON_INVALID_SIGNATURE\x10\x03\x12!\n" +
	"\x1dFAILURE_REASON_DECRYPT_FAILED\x10\x04\x12(\n" +
	"$FAILURE_REASON_UNSUPPORTED_OPERATION\x10\x05\x12'\n" +
	"#FAILURE_REASON_MISSING_PREREQUISITE\x10\x06\x12\x1c\n" +
	"\x18FAILURE_REASON_TSS_ERROR\x10\a\x12\x1a\n" +
	"\x16FAILURE_REASON_ABORTED\x10\b\x12\x1a\n" +
	"\x16FAILURE_REASON_TIMEOUT\x10\t\x12\x19\n" +
	"\x15FAILURE_REASON_REPLAY\x10\n" +
	"B3Z1github.com/vietddude/mpcium-sdk/protocol;protocolb\x06proto3"

var (
	file_mpcium_v1_protocol_proto_rawDescOnce sync.Once
	file_mpcium_v1_protocol_proto_rawDescData []byte
)

func file_mpcium_v1_protocol_proto_rawDescGZIP() []byte {
	file_mpcium_v1_protocol_proto_rawDescOnce.Do(func() {
		file_mpcium_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpcium_v1_protocol_proto_rawDesc), len(file_mpcium_v1_protocol_proto_rawDesc)))
	})
	return file_mpcium_v1_protocol_proto_rawDescData
}

var file_mpcium_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mpcium_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_mpcium_v1_protocol_proto_goTypes = []any{
	(ProtocolType)(0),             // 0: mpcium.protocol.v1.ProtocolType
	(OperationType)(0),            // 1: mpcium.protocol.v1.OperationType
	(ParticipantPhase)(0),         // 2: mpcium.protocol.v1.ParticipantPhase
	(FailureReason)(0),            // 3: mpcium.protocol.v1.FailureReason
	(*SessionParticipant)(nil),    // 4: mpcium.protocol.v1.SessionParticipant
	(*NonHardenedDerivation)(nil), // 5: mpcium.protocol.v1.NonHardenedDerivation
	(*KeygenPayload)(nil),         // 6: mpcium.protocol.v1.KeygenPayload
	(*SignPayload)(nil),           // 7: mpcium.protocol.v1.SignPayload
	(*ResharePayload)(nil),        // 8: mpcium.protocol.v1.ResharePayload
	(*SessionStart)(nil),          // 9: mpcium.protocol.v1.SessionStart
	(*KeyExchangeBegin)(nil),      // 10: mpcium.protocol.v1.KeyExchangeBegin
	(*MpcBegin)(nil),              // 11: mpcium.protocol.v1.MpcBegin
	(*SessionAbort)(nil),          // 12: mpcium.protocol.v1.SessionAbort
	(*ControlMessage)(nil),        // 13: mpcium.protocol.v1.ControlMessage
	(*KeyExchangeHello)(nil),      // 14: mpcium.protocol.v1.KeyExchangeHello
	(*MpcPacket)(nil),             // 15: mpcium.protocol.v1.MpcPacket
	(*PeerMessage)(nil),           // 16: mpcium.protocol.v1.PeerMessage
	(*KeyShareResult)(nil),        // 17: mpcium.protocol.v1.KeyShareResult
	(*SignatureResult)(nil),       // 18: mpcium.protocol.v1.SignatureResult
	(*Result)(nil),                // 19: mpcium.protocol.v1.Result
	(*PeerJoined)(nil),            // 20: mpcium.protocol.v1.PeerJoined
	(*PeerReady)(nil),             // 21: mpcium.protocol.v1.PeerReady
	(*PeerKeyExchangeDone)(nil),   // 22: mpcium.protocol.v1.PeerKeyExchangeDone
	(*PeerFailed)(nil),            // 23: mpcium.protocol.v1.PeerFailed
	(*SessionCompleted)(nil),      // 24: mpcium.protocol.v1.SessionCompleted
	(*SessionFailed)(nil),         // 25: mpcium.protocol.v1.SessionFailed
	(*SessionEvent)(nil),          // 26: mpcium.protocol.v1.SessionEvent
}
var file_mpcium_v1_protocol_proto_depIdxs = []int32{
	5,  // 0: mpcium.protocol.v1.SignPayload.derivation:type_name -> mpcium.protocol.v1.NonHardenedDerivation
	4,  // 1: mpcium.protocol.v1.ResharePayload.new_participants:type_name -> mpcium.protocol.v1.SessionParticipant
	0,  // 2: mpcium.protocol.v1.SessionStart.protocol:type_name -> mpcium.protocol.v1.ProtocolType
	1,  // 3: mpcium.protocol.v1.SessionStart.operation:type_name -> mpcium.protocol.v1.OperationType
	4,  // 4: mpcium.protocol.v1.SessionStart.participants:type_name -> mpcium.protocol.v1.SessionParticipant
	6,  // 5: mpcium.protocol.v1.SessionStart.keygen:type_name -> mpcium.protocol.v1.KeygenPayload
	7,  // 6: mpcium.protocol.v1.SessionStart.sign:type_name -> mpcium.protocol.v1.SignPayload
	8,  // 7: mpcium.protocol.v1.SessionStart.reshare:type_name -> mpcium.protocol.v1.ResharePayload
	3,  // 8: mpcium.protocol.v1.SessionAbort.reason:type_name -> mpcium.protocol.v1.FailureReason
	9,  // 9: mpcium.protocol.v1.ControlMessage.session_start:type_name -> mpcium.protocol.v1.SessionStart
	10, // 10: mpcium.protocol.v1.ControlMessage.key_exchange_begin:type_name -> mpcium.protocol.v1.KeyExchangeBegin
	11, // 11: mpcium.protocol.v1.ControlMessage.mpc_begin:type_name -> mpcium.protocol.v1.MpcBegin
	12, // 12: mpcium.protocol.v1.ControlMessage.session_abort:type_name -> mpcium.protocol.v1.SessionAbort
	2,  // 13: mpcium.protocol.v1.PeerMessage.phase:type_name -> mpcium.protocol.v1.ParticipantPhase
	14, // 14: mpcium.protocol.v1.PeerMessage.key_exchange_hello:type_name -> mpcium.protocol.v1.KeyExchangeHello
	15, // 15: mpcium.protocol.v1.PeerMessage.mpc_packet:type_name -> mpcium.protocol.v1.MpcPacket
	17, // 16: mpcium.protocol.v1.Result.key_share:type_name -> mpcium.protocol.v1.KeyShareResult
	18, // 17: mpcium.protocol.v1.Result.signature:type_name -> mpcium.protocol.v1.SignatureResult
	3,  // 18: mpcium.protocol.v1.PeerFailed.reason:type_name -> mpcium.protocol.v1.FailureReason
	19, // 19: mpcium.protocol.v1.SessionCompleted.result:type_name -> mpcium.protocol.v1.Result
	3,  // 20: mpcium.protocol.v1.SessionFailed.reason:type_name -> mpcium.protocol.v1.FailureReason
	20, // 21: mpcium.protocol.v1.SessionEvent.peer_joined:type_name -> mpcium.protocol.v1.PeerJoined
	21, // 22: mpcium.protocol.v1.SessionEvent.peer_ready:type_name -> mpcium.protocol.v1.PeerReady
	22, // 23: mpcium.protocol.v1.SessionEvent.peer_key_exchange_done:type_name -> mpcium.protocol.v1.PeerKeyExchangeDone
	23, // 24: mpcium.protocol.v1.SessionEvent.peer_failed:type_name -> mpcium.protocol.v1.PeerFailed
	24, // 25: mpcium.protocol.v1.SessionEvent.session_completed:type_name -> mpcium.protocol.v1.SessionCompleted
	25, // 26: mpcium.protocol.v1.SessionEvent.session_failed:type_name -> mpcium.protocol.v1.SessionFailed
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_mpcium_v1_protocol_proto_init() }
func file_mpcium_v1_protocol_proto_init() {
	if File_mpcium_v1_protocol_proto != nil {
		return
	}
	file_mpcium_v1_protocol_proto_msgTypes[5].OneofWrappers = []any{
		(*SessionStart_Keygen)(nil),
		(*SessionStart_Sign)(nil),
		(*SessionStart_Reshare)(nil),
	}
	file_mpcium_v1_protocol_proto_msgTypes[9].OneofWrappers = []any{
		(*ControlMessage_SessionStart)(nil),
		(*ControlMessage_KeyExchangeBegin)(nil),
		(*ControlMessage_MpcBegin)(nil),
		(*ControlMessage_SessionAbort)(nil),
	}
	file_mpcium_v1_protocol_proto_msgTypes[12].OneofWrappers = []any{
		(*PeerMessage_KeyExchangeHello)(nil),
		(*PeerMessage_MpcPacket)(nil),
	}
	file_mpcium_v1_protocol_proto_msgTypes[15].OneofWrappers = []any{
		(*Result_KeyShare)(nil),
		(*Result_Signature)(nil),
	}
	file_mpcium_v1_protocol_proto_msgTypes[22].OneofWrappers = []any{
		(*SessionEvent_PeerJoined)(nil),
		(*SessionEvent_PeerReady)(nil),
		(*SessionEvent_PeerKeyExchangeDone)(nil),
		(*SessionEvent_PeerFailed)(nil),
		(*SessionEvent_SessionCompleted)(nil),
		(*SessionEvent_SessionFailed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpcium_v1_protocol_proto_rawDesc), len(file_mpcium_v1_protocol_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mpcium_v1_protocol_proto_goTypes,
		DependencyIndexes: file_mpcium_v1_protocol_proto_depIdxs,
		EnumInfos:         file_mpcium_v1_protocol_proto_enumTypes,
		MessageInfos:      file_mpcium_v1_protocol_proto_msgTypes,
	}.Build()
	File_mpcium_v1_protocol_proto = out.File
	file_mpcium_v1_protocol_proto_goTypes = nil
	file_mpcium_v1_protocol_proto_depIdxs = nil
}
